# Generated by Django 4.1 on 2022-09-20 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="date_of_completion",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="volume",
            field=models.IntegerField(default=100),
        ),
    ]
