# Generated by Django 4.2.2 on 2023-09-07 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_order_date_of_completion_product_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders_products',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
